bcc_epoch: 0
bcc_augment: true
cm_diagonal_prior_hyp: 0.1
convergence_threshold_hyp: 1.0e-06
weights: ''
cfg: C:\Users\rb01243\OneDrive - University of Surrey\Documents\GitHub\C-YOLOv3\v3-crowd\src\models\yolov3.yaml
data: ../data/single_toy_bcc.yaml
hyp: data\hyps\hyp.scratch.yaml
epochs: 100
batch_size: 20
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs\train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 0
freeze: 0
save_period: -1
local_rank: -1
toggle_save_weights: false
augment: false
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\train\exp11
